name: Build and publish %%IMAGE%%:%%VERSION%% image

on:
  push:
    paths:
      - '%%IMAGE%%/%%VERSION%%/**'
      - '.github/workflows/docker-build-%%IMAGE%%-%%VERSION%%.yml'

env:
  LATEST: %%LATEST%%

jobs:
  build:
    name: Build and publish Docker images
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Extract owner name
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%/*})"
        id: info
      - name: Login to Docker Hub
        run: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ steps.info.outputs.owner }}" --password-stdin
      - name: Build %%IMAGE%% Debian image
        run: docker build -t "${{ steps.info.outputs.owner }}/%%IMAGE%%:%%VERSION%%" "%%IMAGE%%/%%VERSION%%"
      - name: Build %%IMAGE%% Alpine image
        run: docker build -t "${{ steps.info.outputs.owner }}/%%IMAGE%%:%%VERSION%%-alpine" "%%IMAGE%%/%%VERSION%%/alpine"
      - name: Publish %%IMAGE%% Debian image
        if: github.ref == 'refs/heads/master'
        run: docker push "${{ steps.info.outputs.owner }}/%%IMAGE%%:%%VERSION%%"
      - name: Publish %%IMAGE%% Alpine image
        if: github.ref == 'refs/heads/master'
        run: docker push "${{ steps.info.outputs.owner }}/%%IMAGE%%:%%VERSION%%-alpine"
      - name: Update the latest %%IMAGE%% Debian image
        if: env.LATEST == 1 && github.ref == 'refs/heads/master'
        run: |
          docker tag "${{ steps.info.outputs.owner }}/%%IMAGE%%:%%VERSION%%" "${{ steps.info.outputs.owner }}/%%IMAGE%%:latest"
          docker tag "${{ steps.info.outputs.owner }}/%%IMAGE%%:%%VERSION%%-alpine" "${{ steps.info.outputs.owner }}/%%IMAGE%%:latest-alpine"
          docker push "${{ steps.info.outputs.owner }}/%%IMAGE%%:latest"
          docker push "${{ steps.info.outputs.owner }}/%%IMAGE%%:latest-alpine"
