name: Build Edge images

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    paths:
      - '**/Dockerfile.edge'
      - '.github/workflows/build-edge-images.yml'

jobs:
  build_edge:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build edge image
        if: github.ref != 'refs/heads/master'
        run: |
          ./build.sh roswell edge debian
          ./test.sh roswell edge debian
      - name: Build and publish edge image
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          ./build.sh roswell edge debian --push
          ./test.sh roswell edge debian
