name: Build Docker images

on:
  push:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/build-all-images.yml'
      - '**/build.sh'

jobs:
  roswell:
    name: Roswell
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [debian, ubuntu, alpine]

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: fukamachi
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and publish roswell ${{ matrix.target }} images
        env:
          PLATFORM: linux/amd64,linux/arm64
        run: |
          build_arg=""
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            build_arg="--push"
          fi
          for version in `cat roswell/versions | awk -F, '{ print $1 }'`
          do
            ./build.sh roswell $version ${{ matrix.target }} $build_arg
          done

  sbcl:
    name: SBCL
    runs-on: ubuntu-18.04
    needs: roswell
    strategy:
      matrix:
        target: [debian, ubuntu, alpine]

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: fukamachi
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and publish sbcl ${{ matrix.target }} images
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          PLATFORM=linux/amd64
          build_arg=""
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            build_arg="--push"
            PLATFORM=linux/amd64,linux/arm64
          fi
          for version in `cat sbcl/versions | awk -F, '{ print $1 }'`
          do
            ./build.sh sbcl $version ${{ matrix.target }} $build_arg
          done

  ccl:
    name: Clozure CL
    runs-on: ubuntu-18.04
    needs: roswell
    strategy:
      matrix:
        target: [debian, ubuntu, alpine]

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: fukamachi
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and publish ccl ${{ matrix.target }} images
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          PLATFORM=linux/amd64
          build_arg=""
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            build_arg="--push"
            PLATFORM=linux/amd64,linux/arm64
          fi
          for version in `cat ccl/versions | awk -F, '{ print $1 }'`
          do
            ./build.sh ccl $version ${{ matrix.target }} $build_arg
          done
