name: Build Edge images

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    paths:
      - '**/Dockerfile.edge'
      - '.github/workflows/build-edge-images.yml'

jobs:
  build_edge:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: fukamachi
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and publish edge image
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          PLATFORM: linux/amd64,linux/arm64
        run: |
          build_arg=""
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            build_arg="--push"
          fi
          ./build.sh roswell edge debian $build_arg
          ./test.sh roswell edge debian
