name: Build and publish sbcl-bin Docker images

on:
  push:
    paths:
      - 'sbcl-bin/1.4.14/**'

env:
  LATEST: 0

jobs:
  build:
    name: Build and publish Docker images
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Login to Docker Hub
        run: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "fukamachi" --password-stdin
      - name: Build sbcl-bin Debian image
        run: docker build -t "fukamachi/sbcl-bin:1.4.14" "sbcl-bin/1.4.14"
      - name: Build sbcl-bin Alpine image
        run: docker build -t "fukamachi/sbcl-bin:1.4.14-alpine" "sbcl-bin/1.4.14/alpine"
      - name: Publish sbcl-bin Debian image
        run: docker push "fukamachi/sbcl-bin:1.4.14"
      - name: Publish sbcl-bin Alpine image
        run: docker push "fukamachi/sbcl-bin:1.4.14-alpine"
      - name: Update the latest sbcl-bin Debian image
        if: env.LATEST == 1
        run: |
          docker tag "fukamachi/sbcl-bin:1.4.14" "fukamachi/sbcl-bin:latest"
          docker tag "fukamachi/sbcl-bin:1.4.14-alpine" "fukamachi/sbcl-bin:latest-alpine"
          docker push "fukamachi/sbcl-bin:latest"
          docker push "fukamachi/sbcl-bin:latest-alpine"
