name: Build and publish sbcl:1.5.0 image

on:
  push:
    paths:
      - 'sbcl/1.5.0/**'
      - '.github/workflows/docker-build-sbcl-1.5.0.yml'

env:
  LATEST: 0

jobs:
  build:
    name: Build and publish Docker images
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Extract owner name
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%/*})"
        id: info
      - name: Login to Docker Hub
        run: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ steps.info.outputs.owner }}" --password-stdin
      - name: Build sbcl Debian image
        run: docker build -t "${{ steps.info.outputs.owner }}/sbcl:1.5.0" "sbcl/1.5.0"
      - name: Build sbcl Alpine image
        run: docker build -t "${{ steps.info.outputs.owner }}/sbcl:1.5.0-alpine" "sbcl/1.5.0/alpine"
      - name: Publish sbcl Debian image
        if: github.ref == 'refs/heads/master'
        run: docker push "${{ steps.info.outputs.owner }}/sbcl:1.5.0"
      - name: Publish sbcl Alpine image
        if: github.ref == 'refs/heads/master'
        run: docker push "${{ steps.info.outputs.owner }}/sbcl:1.5.0-alpine"
      - name: Update the latest sbcl Debian image
        if: env.LATEST == 1 && github.ref == 'refs/heads/master'
        run: |
          docker tag "${{ steps.info.outputs.owner }}/sbcl:1.5.0" "${{ steps.info.outputs.owner }}/sbcl:latest"
          docker tag "${{ steps.info.outputs.owner }}/sbcl:1.5.0-alpine" "${{ steps.info.outputs.owner }}/sbcl:latest-alpine"
          docker push "${{ steps.info.outputs.owner }}/sbcl:latest"
          docker push "${{ steps.info.outputs.owner }}/sbcl:latest-alpine"
