name: Build and publish roswell:19.09.12.102 image

on:
  push:
    paths:
      - 'roswell/19.09.12.102/**'
      - '.github/workflows/docker-build-roswell-19.09.12.102.yml'

env:
  LATEST: 0

jobs:
  build:
    name: Build and publish Docker images
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Extract owner name
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%/*})"
        id: info
      - name: Login to Docker Hub
        run: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ steps.info.outputs.owner }}" --password-stdin
      - name: Build roswell Debian image
        run: docker build -t "${{ steps.info.outputs.owner }}/roswell:19.09.12.102" "roswell/19.09.12.102"
      - name: Build roswell Alpine image
        run: docker build -t "${{ steps.info.outputs.owner }}/roswell:19.09.12.102-alpine" "roswell/19.09.12.102/alpine"
      - name: Publish roswell Debian image
        if: github.ref == 'refs/heads/master'
        run: docker push "${{ steps.info.outputs.owner }}/roswell:19.09.12.102"
      - name: Publish roswell Alpine image
        if: github.ref == 'refs/heads/master'
        run: docker push "${{ steps.info.outputs.owner }}/roswell:19.09.12.102-alpine"
      - name: Update the latest roswell Debian image
        if: env.LATEST == 1 && github.ref == 'refs/heads/master'
        run: |
          docker tag "${{ steps.info.outputs.owner }}/roswell:19.09.12.102" "${{ steps.info.outputs.owner }}/roswell:latest"
          docker tag "${{ steps.info.outputs.owner }}/roswell:19.09.12.102-alpine" "${{ steps.info.outputs.owner }}/roswell:latest-alpine"
          docker push "${{ steps.info.outputs.owner }}/roswell:latest"
          docker push "${{ steps.info.outputs.owner }}/roswell:latest-alpine"
