name: Lint Dockerfiles

on:
  push:
    paths:
      - '**/*/Dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  autoupdate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install hadolint
        run: |
          curl -L -o ~/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.4/hadolint-$(uname -s)-$(uname -m)"
          chmod 700 ~/hadolint
      - name: Run hadolint
        run: |
          git ls-files --exclude=Dockerfile --ignored | xargs --max-lines=1 ~/hadolint
